#Use secrets instead of env variables in prod
services:
  postgres:
    image: '${IMAGE_NAME}'
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_URL}'
    ports:
      - '${DB_PORTS}'
    restart: always