#Use secrets instead of env variables in prod
spring.application.name=comic-reading-guides
spring.config.import=file:application-local.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

#This should only be used locally, not in production
spring.jpa.hibernate.ddl-auto=update
